[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn codegreen.wsgi --workers 2 --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/auth-status/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
